CREATE TABLE DEPARTMENT
(
ID				BIGINT				PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME			VARCHAR(20)			NOT NULL UNIQUE
);

INSERT INTO DEPARTMENT(NAME) VALUES ('Books');
INSERT INTO DEPARTMENT(NAME) VALUES ('Music');
INSERT INTO DEPARTMENT(NAME) VALUES ('Movie');
INSERT INTO DEPARTMENT(NAME) VALUES ('Computer');
INSERT INTO DEPARTMENT(NAME) VALUES ('Sport');
INSERT INTO DEPARTMENT(NAME) VALUES ('Clothing');



CREATE TABLE SUB_DEPARTMENT
(
ID				BIGINT				PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
DEPARTMENT_ID	BIGINT				NOT NULL REFERENCES DEPARTMENT(ID),
NAME			VARCHAR(100)		NOT NULL
);

ALTER TABLE SUB_DEPARTMENT ADD UNIQUE(DEPARTMENT_ID, NAME);

INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'Arts & Photography');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'Business & Money');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'Computer & Technology');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'Education & Teching');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'Engineering & Transportation');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'History');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Books'), 'Science and Math');

INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Blues');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Classical');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Country');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Jazz');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Pop');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Rap & Hip-Hop');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Music'), 'Rock');

INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Movie'), 'Action & Adventure');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Movie'), 'Comedy');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Movie'), 'Kids & Family');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Movie'), 'Mystery & Thrillers');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Movie'), 'Romance');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Movie'), 'Science Fiction');

INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'Laptops & Tablets');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'Computer Accessories & Peripherals');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'External drives, mice, networking & more');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'Computer Parts & Components');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'Printers & Ink');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'Office & School Supplies');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Computer'), 'Networking');

INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Sport'), 'Athletic Clothing');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Sport'), 'Exercise & Fitness');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Sport'), 'Hunting & Fishing');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Sport'), 'Team Sports');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Sport'), 'Golf');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Sport'), 'Sports Collectibles');

INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Men Clothing');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Men Shoes');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Men Jewelry');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Men Watches');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Women Clothing');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Women Shoes');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Women Jewelry');
INSERT INTO SUB_DEPARTMENT(DEPARTMENT_ID, NAME) VALUES ((SELECT ID FROM DEPARTMENT WHERE NAME='Clothing'), 'Women Watches');
